@startuml
skinparam componentStyle uml2
skinparam component {
    ArrowColor black
    BorderColor blue
}
node "Business Number" as bn {
    [Business Number Service] as bns
}
node "Partner" as pdv {
    [Person Service] as ps
    [Links Service] as ls

    ps --> ls
}
node "Tasks" as tasks {
    [Tasks Service] as ts
}

node "Claim" as main {
    [Announce] as a
    [Case] as c
}
    [Link Partner] as lp

    a -u-> c
    a -u-> bns : call&retry
    a -left-> ps : gentle degradation
    a --> ts : choregraphy (message)
    c -right-> lp : saga
    a -> lp : saga
    lp <- ls : poll
    c -> ts : choregraphy (message)
    c -u-> bns : call&retry
    c -> ps : gentle degradation

@enduml
