@startuml
skinparam componentStyle uml2
skinparam component {
    ArrowColor black
    BorderColor blue
}
node "Business Number" as bn {
    [Business Number Service] as bns
}
node "Partner" as pdv {
    [Person Service] as ps
    [Links Service] as ls

    ps --> ls
}
node "Tasks" as tasks {
    [Tasks Service] as ts
}

node "Claim" as main {
    [Case] as c
    [Link Partner] as lp
}


    c -left-> ts : choregraphy (message)
    c --> lp : saga
    lp <- ls : poll
    c -u-> bns : call&retry
    ps -u-> bns : call&retry
    c -> ps : update after event

@enduml
