@startuml
skinparam node {
    BackgroundColor light
    ArrowColor blue
}
skinparam note {
    BackgroundColor light
    BorderColor blue
}
node "Business Number" as bn
node "Partner" as pdv
node "Claim" as main
node "Tasks" as tasks

main -up-> bn
pdv -up-> bn
main -right-> pdv
main -left-> tasks
@enduml
