version: '3'
services:
  business-number-service:
    container_name: "businessnumber"
    image: sandbox/businessnumber:BETA
    ports:
      - 8080
  person-db:
    container_name: "person-db"
    image: postgres:9.6.8-alpine
    environment:
      POSTGRES_PASSWORD: 123456
      POSTGRES_USER: person_user
    ports:
      - "5432:5432"
  person-service:
    container_name: "person-service"
    image: sandbox/person-application:BETA
    ports:
      - "9080:8080"
    environment:
      person.db.url: jdbc:postgresql://db:5432/person_user
      person.db.user: person_user
      person.db.pass: 123456
      person.db.driver: org.postgresql.Driver
      businessnumber.url: http://bn:8080/business-number
    links:
      - person-db:db
      - business-number-service:bn