package MicroserviceSandbox.patches.buildTypes

import jetbrains.buildServer.configs.kotlin.v2017_2.*
import jetbrains.buildServer.configs.kotlin.v2017_2.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, change the buildType with uuid = '86a5392d-63ce-4be0-9f16-f32f89b04336' (id = 'MicroserviceSandbox_Build')
accordingly and delete the patch script.
*/
changeBuildType("86a5392d-63ce-4be0-9f16-f32f89b04336") {
    check(artifactRules == "+:**/case/case-infra/target/pitreports => pitreports") {
        "Unexpected option value: artifactRules = $artifactRules"
    }
    artifactRules = "case/case-infra/target/pitreports => pitreports"
}
