package MicroserviceSandbox.patches.vcsRoots

import jetbrains.buildServer.configs.kotlin.v2017_2.*
import jetbrains.buildServer.configs.kotlin.v2017_2.ui.*
import jetbrains.buildServer.configs.kotlin.v2017_2.vcs.GitVcsRoot

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, change the vcsRoot with uuid = 'e30321e5-6aeb-4e0b-8ebb-60ecc2de0010' (id = 'MicroserviceSandbox_HttpsGithubComMcKrattMicroserviceSandboxRefsHeadsMaster')
accordingly and delete the patch script.
*/
changeVcsRoot("e30321e5-6aeb-4e0b-8ebb-60ecc2de0010") {
    val expected = GitVcsRoot({
        uuid = "e30321e5-6aeb-4e0b-8ebb-60ecc2de0010"
        id = "MicroserviceSandbox_HttpsGithubComMcKrattMicroserviceSandboxRefsHeadsMaster"
        name = "https://github.com/McKratt/microservice-sandbox#refs/heads/master"
        url = "https://github.com/McKratt/microservice-sandbox"
        authMethod = password {
            userName = "McKratt"
            password = "credentialsJSON:5f460ae0-2380-4763-8bb9-7c6df62ad0e8"
        }
    })

    check(this == expected) {
        "Unexpected VCS root settings"
    }

    (this as GitVcsRoot).apply {
        authMethod = password {
            userName = "McKratt"
            password = "credentialsJSON:5f460ae0-2380-4763-8bb9-7c6df62ad0e8"
        }
    }

}
