package MicroserviceSandbox.patches.projects

import jetbrains.buildServer.configs.kotlin.v2017_2.*
import jetbrains.buildServer.configs.kotlin.v2017_2.Project
import jetbrains.buildServer.configs.kotlin.v2017_2.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, change the project with uuid = '4c256d8d-50e3-4e11-bb36-ad7074c9506a' (id = 'MicroserviceSandbox')
accordingly and delete the patch script.
*/
changeProject("4c256d8d-50e3-4e11-bb36-ad7074c9506a") {
    features {
        add {
            feature {
                type = "ReportTab"
                id = "PROJECT_EXT_1"
                param("startPage", "pitreports/index.html")
                param("title", "PIT Report")
                param("type", "BuildReportTab")
            }
        }
    }
}
